=== thatVaddiguy/radio-listing/radio.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT radioListing (radioStation+)>
<!ELEMENT radioStation (radioShow+)>
<!ELEMENT radioShow (showTitle,showAltTitle*,startTime,duration,description)>
<!ELEMENT showTitle (#PCDATA)>
<!ELEMENT showAltTitle (#PCDATA)>
<!ELEMENT startTime (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST radioStation name CDATA #REQUIRED>

=== thatVaddiguy/radio-listing/RadioML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="radioStyle.xsl"?>
<!DOCTYPE radioListing SYSTEM "radio.dtd">
<radioListing>
  <radioStation name="Radio2">
    <radioShow>
      <showTitle>Sounds of the 80s</showTitle>
      <startTime>00:00</startTime>
      <duration>2 hours</duration>
      <description>Sara looks back at the 24 hour danceathon for Comic Relief</description>
      <presenters>Sara</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Radio 2 Playlists</showTitle>
      <showAltTitle>Radio 2's Folk Playlist</showAltTitle>
      <startTime>02:03</startTime>
      <duration>1 hour</duration>
      <description>Mark Radcliffe's selection of folk,roots and acoustic music</description>
      <presenters>Mark Radcliffe</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Radio 2 Playlists</showTitle>
      <showAltTitle>Radio 2 Playlist: Morning Acoustic</showAltTitle>
      <startTime>03:03</startTime>
      <duration>1 hour</duration>
      <description>New and older tracks both unplugged and acoustic, with OJ Borg</description>
      <presenters>OJ Borg</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Radio 2 Playlists</showTitle>
      <showAltTitle>Radio 2 Playlist: Wednesday Workout</showAltTitle>
      <startTime>04:03</startTime>
      <duration>1 hour</duration>
      <description>OJ Borg dons his wristbands and legwarmers for another Wednesday Workout</description>
      <presenters>OJ Borg</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Vanessa Feltz</showTitle>
      <startTime>05:00</startTime>
      <duration>1.5 hour</duration>
      <description>Vanessa Feltz presents music,chat and a first look at the day's newspapers</description>
      <presenters>Vanessa Feltz</presenters>
    </radioShow>
    <radioShow>
      <showTitle>The Chris Evans Breakfast Show</showTitle>
      <startTime>06:30</startTime>
      <duration>3 hours</duration>
      <description>Chris Evans presents a fully interactive show for all the family</description>
      <presenters>Chris Evans</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Ken Bruce</showTitle>
      <showAltTitle>Stella Parton chooses the Tracks of My Years</showAltTitle>
      <startTime>09:30</startTime>
      <duration>2.5 hours</duration>
      <description>Stella Parton chooses the Tracks of My Years , plus the PopMaster Music Quiz</description>
      <presenters>Stella Parton</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Jeremy Vine</showTitle>
      <startTime>12:00</startTime>
      <duration>2 hour</duration>
      <description>Jeremy Vine presents news,views and live guests</description>
      <presenters>Jeremy Vine</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Steve Wright in the Afternoon </showTitle>
      <showAltTitle>Professor Charles Spence, Shaun Williamson, Lee Mack and Griff Rhys Jones</showAltTitle>
      <startTime>14:00</startTime>
      <duration>3 hours</duration>
      <description>Steve talks to Professor Charles Spence, Shaun Williamson, Lee Mack and Griff Rhys Jones </description>
      <presenters>Steve Wright</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Simon Mayo Drivetime </showTitle>
      <showAltTitle>John Bishop</showAltTitle>
      <startTime>17:05</startTime>
      <duration>2 hours</duration>
      <description>John Bishop joins Simon to discuss the second series of 'in Conversation With' on 'W' </description>
      <presenters>John Bishop</presenters>
    </radioShow>
    <radioShow>
      <showTitle>The Folk SHow with Mark Radcliffe </showTitle>
      <showAltTitle>Folk Awards Preview</showAltTitle>
      <startTime>19:00</startTime>
      <duration>1 hour</duration>
      <description>Mark looks ahead to next week's BBC Radoi 2 Folk Awards</description>
      <presenters>Mark Radcliffe</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Jo Whiley </showTitle>
      <showAltTitle>Vinyl Revival from Paul Simon</showAltTitle>
      <startTime>20:00</startTime>
      <duration>2 hours</duration>
      <description>Jo has this week's Vinyl Revival; 'Graceland' and the new favourite thing from Gorillaz</description>
      <presenters>Jo Whiley</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Fairport at 50</showTitle>
      <startTime>22:00</startTime>
      <duration>1 hour</duration>
      <description>Fairport at 50 celebrates the histoy and legacy of Fairport Convention</description>
    </radioShow>
    <radioShow>
      <showTitle>David Attenborough and the Natural History of Folk</showTitle>
      <startTime>23:00</startTime>
      <duration>1 hour</duration>
      <description>Nature broadcaster David Attenborough on his early TV work - producing folk music shows</description>
      <presenters>David Attenborough</presenters>
    </radioShow>
  </radioStation>
  <radioStation name="Radio3">
    <radioShow>
      <showTitle>Through the Night </showTitle>
      <showAltTitle>Proms 2015: Danish National Symphony Orchestra</showAltTitle>
      <startTime>00:30</startTime>
      <duration>6 hours</duration>
      <description>John Shea presents the Danish National Symphony Orchestra performing music by Nielsen</description>
      <presenters>John Shea</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Breakfast </showTitle>
      <showAltTitle>Wednesday - Petroc Trelawny</showAltTitle>
      <startTime>06:30</startTime>
      <duration>2.5 hours</duration>
      <description>Petroc Trelawny presents Radio 3's classical breakfast show featuring listener requests</description>
      <presenters>Petroc Trelawny</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Essential Classics</showTitle>
      <showAltTitle>Wednesday - Rob Cowan with Ken Hom</showAltTitle>
      <startTime>09:00</startTime>
      <duration>3 hours</duration>
      <description>With Artist of the Week: Nikolaj Znaider, featured performing Brahm's Violin Sonata No 1.</description>
      <presenters>Rob Cowan</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Composer Of the Week </showTitle>
      <showAltTitle>Sergei Rachmaninov(1873-1943)</showAltTitle>
      <startTime>12:00</startTime>
      <duration>1 hour</duration>
      <description>3/5 Donald Macleod discusses Rachmaninov's epic and fiendishly difficult Third Piano Concerto</description>
      <presenters>DOnald Macleod</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Radio 3 Lunchtime Concert </showTitle>
      <showAltTitle>Machynlleth and Gower Festivals 2016</showAltTitle>
      <startTime>13:00</startTime>
      <duration>1 hour</duration>
      <description>2/4 With Anna Stephany in French songs and the Schubert Ensemble in a piano quartet by Faure</description>
      <presenters>Anna Stephany</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Afternoon on 3</showTitle>
      <showAltTitle>Wednesday- BBC singers at the BBC Proms Dubai</showAltTitle>
      <startTime>14:00</startTime>
      <duration>1.5 hours</duration>
      <description>BBC Singers in music by Stanford, Tippet, Dove, Warlock, Cowie, Grainger and Wikeley</description>
    </radioShow>
    <radioShow>
      <showTitle>Choral Evensong</showTitle>
      <showAltTitle>Choral Evening Prayer - Liverpool Metropolitan Cathedral</showAltTitle>
      <startTime>15:30</startTime>
      <duration>1 hour</duration>
      <description>From Liverpool Metropolitan Cathedral</description>
    </radioShow>
    <radioShow>
      <showTitle>In Tune </showTitle>
      <showAltTitle>Wednesday - Sean Rafferty</showAltTitle>
      <startTime>16:30</startTime>
      <duration>2 hours</duration>
      <description>Sean Rafferty's guests include pianist Vadym Kholodenko</description>
      <presenters>Sean Rafferty</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Composer Of the Week </showTitle>
      <showAltTitle>Sergei Rachmaninov(1873-1943)</showAltTitle>
      <startTime>18:30</startTime>
      <duration>1 hour</duration>
      <description>3/5 Donald Macleod discusses Rachmaninov's epic and fiendishly difficult Third Piano Concerto</description>
      <presenters>Donald Macleod</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Radio 3 in Concert </showTitle>
      <showAltTitle>Joshua Bell and Sam Haywood</showAltTitle>
      <startTime>19:30</startTime>
      <duration>2.5 hours</duration>
      <description>Joshua Bell and Sam Haywood - Beethoven, Brahms, Kernis, Ysaye, Rachmaninov,Sarasate</description>
      <presenters>Joshua Bell and Sam Haywood</presenters>
    </radioShow>
    <radioShow>
      <showTitle>Free Thinking</showTitle>
      <showAltTitle>Festival 2017, The never-ending Workday</showAltTitle>
      <startTime>22:00</startTime>
      <duration>0.75 hour</duration>
      <description>8/16 Mathew Sweet introduces a discussion exploring the history of the workplace</description>
      <presenters>Mathew Sweet</presenters>
    </radioShow>
    <radioShow>
      <showTitle>The Essay</showTitle>
      <showAltTitle>Free Thinking 2017, England's First European</showAltTitle>
      <startTime>22:45</startTime>
      <duration>0.25 hour</duration>
      <description>8/10 Exploring Fynes Moryson's An Itinerary, a European travel book form the early 17th century</description>
    </radioShow>
    <radioShow>
      <showTitle>Late Junction</showTitle>
      <showAltTitle>Late Junction Sessions - Danny L Harle and Pawel Siwczak</showAltTitle>
      <startTime>23:00</startTime>
      <duration>1 hour</duration>
      <description>With a session form popproducer Danny L Harle and early keyboard specialist Pawel Siwczak</description>
    </radioShow>
  </radioStation>
  <radioStation name="radio4">
    <radioShow>
      <showTitle>Midnight News </showTitle>
      <startTime>00:00</startTime>
      <duration>0.5 hour</duration>
